version: "1"
rules:
  - base: master                    # Required; target branch
    upstream: flathub:master        # Required; must be in the same fork network
    mergeMethod: rebase             # One of [none, merge, squash, rebase, hardreset]
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
label: ":arrow_heading_down: pull"
